name: 'mercurios'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'mercurios'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  mercurios:
    # Config indicated by + and applies to all files under models/
    +materialized: view
    +schema: analytics
    
    staging:
      +materialized: view
      +schema: staging
      
    intermediate:
      +materialized: view
      +schema: intermediate
      
    marts:
      +materialized: table
      +schema: marts
      
      inventory:
        +schema: marts_inventory
        
      sales:
        +schema: marts_sales

vars:
  # Define warehouse-specific variables
  warehouse_size: 'XSMALL'
  auto_suspend: 60
  
  # Define data freshness thresholds
  max_data_freshness_hours: 24
  
  # Define inventory-specific thresholds
  low_stock_threshold: 5
  excess_stock_threshold: 100
  days_of_supply_warning: 7
  days_of_supply_critical: 3
