mercurios:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: VRXDFZX-ZZ95717
      user: JULIUSRECHENBACH
      # Using key pair authentication instead of password
      private_key_path: /Users/juliusrechenbach/.ssh/snowflake/rsa_key.p8
      role: MERCURIOS_DEVELOPER
      database: MERCURIOS_DATA
      warehouse: MERCURIOS_DEV_WH
      schema: staging
      threads: 4
      client_session_keep_alive: True
      reuse_connections: True
      connect_retries: 3
      connect_timeout: 30
      retry_on_database_errors: True
      query_tag: dbt_mercurios_dev
      
    prod:
      type: snowflake
      account: VRXDFZX-ZZ95717
      user: JULIUSRECHENBACH
      # Using key pair authentication instead of password
      private_key_path: /Users/juliusrechenbach/.ssh/snowflake/rsa_key.p8
      role: MERCURIOS_ADMIN
      database: MERCURIOS_DATA
      warehouse: MERCURIOS_ANALYTICS_WH
      schema: marts
      threads: 4
      client_session_keep_alive: True
      reuse_connections: True
      connect_retries: 3
      connect_timeout: 30
      retry_on_database_errors: True
      query_tag: dbt_mercurios_prod
