
    -- Create a view to monitor dashboard costs
    CREATE OR REPLACE VIEW MERCURIOS_DATA.ADMIN.DASHBOARD_COST_MONITORING AS
    SELECT 
      DATE_TRUNC('DAY', START_TIME) AS DATE,
      COUNT(*) AS QUERY_COUNT,
      SUM(TOTAL_ELAPSED_TIME)/1000/60 AS RUNTIME_MINUTES,
      SUM(TOTAL_ELAPSED_TIME)/1000/60/60 * 
        CASE 
          WHEN WAREHOUSE_SIZE = 'XSMALL' THEN 1
          WHEN WAREHOUSE_SIZE = 'SMALL' THEN 2
          ELSE 4
        END AS ESTIMATED_CREDITS
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_DATE())
    AND QUERY_TEXT ILIKE '%BUSINESS_DASHBOARD%'
    GROUP BY 1
    ORDER BY 1 DESC;
    
    -- Tasks will remain suspended until explicitly resumed
    -- To resume tasks, run:
    -- ALTER TASK MERCURIOS_DATA.ADMIN.REFRESH_DASHBOARD_MV RESUME;
    