-- Emergency Snowflake Cost Reduction Commands
-- Run these commands one by one in the Snowflake console

-- 1. Suspend all warehouses immediately
ALTER WAREHOUSE MERCURIOS_LOADING_WH SUSPEND;
ALTER WAREHOUSE MERCURIOS_ANALYTICS_WH SUSPEND;
ALTER WAREHOUSE MERCURIOS_DEV_WH SUSPEND;
ALTER WAREHOUSE COMPUTE_WH SUSPEND IF EXISTS;
ALTER WAREHOUSE FIVETRAN_WAREHOUSE SUSPEND IF EXISTS;

-- 2. Set aggressive auto-suspend timeouts (1 minute)
ALTER WAREHOUSE MERCURIOS_LOADING_WH SET AUTO_SUSPEND = 60;
ALTER WAREHOUSE MERCURIOS_ANALYTICS_WH SET AUTO_SUSPEND = 60;
ALTER WAREHOUSE MERCURIOS_DEV_WH SET AUTO_SUSPEND = 60;
ALTER WAREHOUSE COMPUTE_WH SET AUTO_SUSPEND = 60 IF EXISTS;
ALTER WAREHOUSE FIVETRAN_WAREHOUSE SET AUTO_SUSPEND = 60 IF EXISTS;

-- 3. Reduce warehouse sizes to minimum
ALTER WAREHOUSE MERCURIOS_LOADING_WH SET WAREHOUSE_SIZE = 'XSMALL';
ALTER WAREHOUSE MERCURIOS_ANALYTICS_WH SET WAREHOUSE_SIZE = 'XSMALL';
ALTER WAREHOUSE MERCURIOS_DEV_WH SET WAREHOUSE_SIZE = 'XSMALL';
ALTER WAREHOUSE COMPUTE_WH SET WAREHOUSE_SIZE = 'XSMALL' IF EXISTS;
ALTER WAREHOUSE FIVETRAN_WAREHOUSE SET WAREHOUSE_SIZE = 'XSMALL' IF EXISTS;

-- 4. Disable multi-cluster warehouses
ALTER WAREHOUSE MERCURIOS_LOADING_WH SET MAX_CLUSTER_COUNT = 1, MIN_CLUSTER_COUNT = 1;
ALTER WAREHOUSE MERCURIOS_ANALYTICS_WH SET MAX_CLUSTER_COUNT = 1, MIN_CLUSTER_COUNT = 1;
ALTER WAREHOUSE MERCURIOS_DEV_WH SET MAX_CLUSTER_COUNT = 1, MIN_CLUSTER_COUNT = 1;

-- 5. Set scaling policy to standard (less aggressive)
ALTER WAREHOUSE MERCURIOS_LOADING_WH SET SCALING_POLICY = 'STANDARD';
ALTER WAREHOUSE MERCURIOS_ANALYTICS_WH SET SCALING_POLICY = 'STANDARD';
ALTER WAREHOUSE MERCURIOS_DEV_WH SET SCALING_POLICY = 'STANDARD';

-- 6. Check current warehouse settings to confirm changes
SHOW WAREHOUSES;
