-- Final Fix for Snowflake Access Issues
-- This script addresses the root causes of the access issues

-- Step 1: Use SECURITYADMIN role for role management
USE ROLE SECURITYADMIN;

-- Step 2: Create a secondary role for accessing Fivetran data
-- This role will be used specifically for accessing Fivetran data
CREATE ROLE IF NOT EXISTS MERCURIOS_FIVETRAN_ACCESS;
GRANT ROLE MERCURIOS_FIVETRAN_ACCESS TO ROLE MERCURIOS_ADMIN;
GRANT ROLE MERCURIOS_FIVETRAN_ACCESS TO ROLE MERCURIOS_ANALYST;
GRANT ROLE MERCURIOS_FIVETRAN_ACCESS TO ROLE MERCURIOS_DEVELOPER;
GRANT ROLE MERCURIOS_FIVETRAN_ACCESS TO USER JULIUSRECHENBACH;

-- Step 3: Grant the Fivetran service role to your user
USE ROLE ACCOUNTADMIN;
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO USER JULIUSRECHENBACH;

-- Step 4: Grant the Fivetran service role to other roles
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE MERCURIOS_ADMIN;
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE MERCURIOS_ANALYST;
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE MERCURIOS_DEVELOPER;

-- Step 5: Grant the secondary role access to the Fivetran service role
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE MERCURIOS_FIVETRAN_ACCESS;

-- Step 6: Grant usage on database to all roles
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_FIVETRAN_ACCESS;

-- Step 7: Grant specific access to each Fivetran schema
-- For Google Analytics 4
GRANT USAGE ON SCHEMA MERCURIOS_DATA.GOOGLE_ANALYTICS_4 TO ROLE MERCURIOS_FIVETRAN_ACCESS;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.GOOGLE_ANALYTICS_4 TO ROLE MERCURIOS_FIVETRAN_ACCESS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.GOOGLE_ANALYTICS_4 TO ROLE MERCURIOS_FIVETRAN_ACCESS;

-- For Klaviyo
GRANT USAGE ON SCHEMA MERCURIOS_DATA.KLAVIYO TO ROLE MERCURIOS_FIVETRAN_ACCESS;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.KLAVIYO TO ROLE MERCURIOS_FIVETRAN_ACCESS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.KLAVIYO TO ROLE MERCURIOS_FIVETRAN_ACCESS;

-- For Klaviyo_Klaviyo
GRANT USAGE ON SCHEMA MERCURIOS_DATA.KLAVIYO_KLAVIYO TO ROLE MERCURIOS_FIVETRAN_ACCESS;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.KLAVIYO_KLAVIYO TO ROLE MERCURIOS_FIVETRAN_ACCESS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.KLAVIYO_KLAVIYO TO ROLE MERCURIOS_FIVETRAN_ACCESS;

-- For Klaviyo_INT_Klaviyo
GRANT USAGE ON SCHEMA MERCURIOS_DATA.KLAVIYO_INT_KLAVIYO TO ROLE MERCURIOS_FIVETRAN_ACCESS;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.KLAVIYO_INT_KLAVIYO TO ROLE MERCURIOS_FIVETRAN_ACCESS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.KLAVIYO_INT_KLAVIYO TO ROLE MERCURIOS_FIVETRAN_ACCESS;

-- For Klaviyo_STG_Klaviyo
GRANT USAGE ON SCHEMA MERCURIOS_DATA.KLAVIYO_STG_KLAVIYO TO ROLE MERCURIOS_FIVETRAN_ACCESS;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.KLAVIYO_STG_KLAVIYO TO ROLE MERCURIOS_FIVETRAN_ACCESS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.KLAVIYO_STG_KLAVIYO TO ROLE MERCURIOS_FIVETRAN_ACCESS;

-- For Fivetran Metadata
GRANT USAGE ON SCHEMA MERCURIOS_DATA.FIVETRAN_METADATA TO ROLE MERCURIOS_FIVETRAN_ACCESS;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.FIVETRAN_METADATA TO ROLE MERCURIOS_FIVETRAN_ACCESS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.FIVETRAN_METADATA TO ROLE MERCURIOS_FIVETRAN_ACCESS;

-- For Fivetran_ARMED_UNLEADED_STAGING
GRANT USAGE ON SCHEMA MERCURIOS_DATA.FIVETRAN_ARMED_UNLEADED_STAGING TO ROLE MERCURIOS_FIVETRAN_ACCESS;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.FIVETRAN_ARMED_UNLEADED_STAGING TO ROLE MERCURIOS_FIVETRAN_ACCESS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.FIVETRAN_ARMED_UNLEADED_STAGING TO ROLE MERCURIOS_FIVETRAN_ACCESS;

-- Step 8: Switch to the Fivetran service role to test access
USE ROLE MERCURIOS_FIVETRAN_SERVICE;
SHOW SCHEMAS IN DATABASE MERCURIOS_DATA;
