-- Run as ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;

-- Grant all privileges on database to MERCURIOS_DEVELOPER role
GRANT ALL PRIVILEGES ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;

-- Grant schema usage
GRANT USAGE ON ALL SCHEMAS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;

-- Grant table access
GRANT SELECT ON ALL TABLES IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA MERCURIOS_DATA.STAGING TO ROLE MERCURIOS_DEVELOPER;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA MERCURIOS_DATA.INTERMEDIATE TO ROLE MERCURIOS_DEVELOPER;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA MERCURIOS_DATA.MARTS TO ROLE MERCURIOS_DEVELOPER;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.STAGING TO ROLE MERCURIOS_DEVELOPER;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.INTERMEDIATE TO ROLE MERCURIOS_DEVELOPER;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.MARTS TO ROLE MERCURIOS_DEVELOPER;

-- Grant view access
GRANT SELECT ON ALL VIEWS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;

-- Grant create privileges
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FUNCTION, CREATE PROCEDURE ON SCHEMA MERCURIOS_DATA.STAGING TO ROLE MERCURIOS_DEVELOPER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FUNCTION, CREATE PROCEDURE ON SCHEMA MERCURIOS_DATA.INTERMEDIATE TO ROLE MERCURIOS_DEVELOPER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FUNCTION, CREATE PROCEDURE ON SCHEMA MERCURIOS_DATA.MARTS TO ROLE MERCURIOS_DEVELOPER;

-- Grant warehouse usage
GRANT USAGE, OPERATE ON WAREHOUSE MERCURIOS_DEV_WH TO ROLE MERCURIOS_DEVELOPER;
GRANT MONITOR ON WAREHOUSE MERCURIOS_DEV_WH TO ROLE MERCURIOS_DEVELOPER;

-- Ensure user has the MERCURIOS_DEVELOPER role
GRANT ROLE MERCURIOS_DEVELOPER TO USER JULIUSRECHENBACH;

-- Set default role for the user
ALTER USER JULIUSRECHENBACH SET DEFAULT_ROLE = MERCURIOS_DEVELOPER;

-- Create missing schemas if they don't exist
CREATE SCHEMA IF NOT EXISTS MERCURIOS_DATA.STAGING;
CREATE SCHEMA IF NOT EXISTS MERCURIOS_DATA.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS MERCURIOS_DATA.MARTS;

-- Create monitoring schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS MERCURIOS_DATA.MONITORING;
GRANT ALL PRIVILEGES ON SCHEMA MERCURIOS_DATA.MONITORING TO ROLE MERCURIOS_DEVELOPER;
