-- Run as ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;

-- Grant necessary privileges to MERCURIOS_DEVELOPER role
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_DEVELOPER;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.STAGING TO ROLE MERCURIOS_DEVELOPER;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.INTERMEDIATE TO ROLE MERCURIOS_DEVELOPER;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.MARTS TO ROLE MERCURIOS_DEVELOPER;

-- Grant read privileges on source data
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_DEVELOPER;

-- Grant write privileges on target schemas
GRANT CREATE TABLE ON SCHEMA MERCURIOS_DATA.STAGING TO ROLE MERCURIOS_DEVELOPER;
GRANT CREATE VIEW ON SCHEMA MERCURIOS_DATA.STAGING TO ROLE MERCURIOS_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA MERCURIOS_DATA.INTERMEDIATE TO ROLE MERCURIOS_DEVELOPER;
GRANT CREATE VIEW ON SCHEMA MERCURIOS_DATA.INTERMEDIATE TO ROLE MERCURIOS_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA MERCURIOS_DATA.MARTS TO ROLE MERCURIOS_DEVELOPER;
GRANT CREATE VIEW ON SCHEMA MERCURIOS_DATA.MARTS TO ROLE MERCURIOS_DEVELOPER;

-- Grant warehouse usage
GRANT USAGE ON WAREHOUSE MERCURIOS_DEV_WH TO ROLE MERCURIOS_DEVELOPER;

-- Create monitoring schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS MERCURIOS_DATA.MONITORING;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.MONITORING TO ROLE MERCURIOS_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA MERCURIOS_DATA.MONITORING TO ROLE MERCURIOS_DEVELOPER;
GRANT CREATE VIEW ON SCHEMA MERCURIOS_DATA.MONITORING TO ROLE MERCURIOS_DEVELOPER;

-- Create schemas if they don't exist
CREATE SCHEMA IF NOT EXISTS MERCURIOS_DATA.STAGING;
CREATE SCHEMA IF NOT EXISTS MERCURIOS_DATA.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS MERCURIOS_DATA.MARTS;

-- Ensure all necessary schemas exist for the dbt models
GRANT OWNERSHIP ON SCHEMA MERCURIOS_DATA.STAGING TO ROLE MERCURIOS_DEVELOPER;
GRANT OWNERSHIP ON SCHEMA MERCURIOS_DATA.INTERMEDIATE TO ROLE MERCURIOS_DEVELOPER;
GRANT OWNERSHIP ON SCHEMA MERCURIOS_DATA.MARTS TO ROLE MERCURIOS_DEVELOPER;
