-- Fix Snowflake Access for Fivetran-managed Schemas
-- This script resolves access issues for Fivetran-managed schemas in Snowflake

-- Step 1: Grant the Fivetran service role to the user
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO USER JULIUSRECHENBACH;

-- Step 2: Grant the Fivetran service role to other roles
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE ACCOUNTADMIN;
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE MERCURIOS_ADMIN;
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE MERCURIOS_ANALYST;
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE MERCURIOS_DEVELOPER;

-- Step 3: Grant usage on database to all roles
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;

-- Step 4: Grant usage on all schemas in database to all roles
GRANT USAGE ON ALL SCHEMAS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;

-- Step 5: Grant select on all tables in all schemas to all roles
GRANT SELECT ON ALL TABLES IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;

-- Step 6: Grant select on future tables in all schemas to all roles
GRANT SELECT ON FUTURE TABLES IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON FUTURE TABLES IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON FUTURE TABLES IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;

-- Step 7: Grant select on all views in all schemas to all roles
GRANT SELECT ON ALL VIEWS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL VIEWS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON ALL VIEWS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;

-- Step 8: Grant select on future views in all schemas to all roles
GRANT SELECT ON FUTURE VIEWS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON FUTURE VIEWS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;

-- Step 9: Grant specific access to each Fivetran schema
-- For Google Analytics 4
GRANT USAGE ON SCHEMA MERCURIOS_DATA.GOOGLE_ANALYTICS_4 TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.GOOGLE_ANALYTICS_4 TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.GOOGLE_ANALYTICS_4 TO ROLE MERCURIOS_DEVELOPER;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.GOOGLE_ANALYTICS_4 TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.GOOGLE_ANALYTICS_4 TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.GOOGLE_ANALYTICS_4 TO ROLE MERCURIOS_DEVELOPER;

-- For Klaviyo
GRANT USAGE ON SCHEMA MERCURIOS_DATA.KLAVIYO TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.KLAVIYO TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.KLAVIYO TO ROLE MERCURIOS_DEVELOPER;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.KLAVIYO TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.KLAVIYO TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.KLAVIYO TO ROLE MERCURIOS_DEVELOPER;

-- For Klaviyo_Klaviyo
GRANT USAGE ON SCHEMA MERCURIOS_DATA.KLAVIYO_KLAVIYO TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.KLAVIYO_KLAVIYO TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.KLAVIYO_KLAVIYO TO ROLE MERCURIOS_DEVELOPER;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.KLAVIYO_KLAVIYO TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.KLAVIYO_KLAVIYO TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.KLAVIYO_KLAVIYO TO ROLE MERCURIOS_DEVELOPER;

-- For Fivetran Metadata
GRANT USAGE ON SCHEMA MERCURIOS_DATA.FIVETRAN_METADATA TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.FIVETRAN_METADATA TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.FIVETRAN_METADATA TO ROLE MERCURIOS_DEVELOPER;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.FIVETRAN_METADATA TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.FIVETRAN_METADATA TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.FIVETRAN_METADATA TO ROLE MERCURIOS_DEVELOPER;
