-- Fix Fivetran Access in Snowflake
-- This script focuses on the critical IMPORTED PRIVILEGES needed for Fivetran schemas

-- Step 1: Grant IMPORTED PRIVILEGES on database
-- This is the most critical step for accessing Fivetran-managed schemas
GRANT IMPORTED PRIVILEGES ON DATABASE MERCURIOS_DATA TO ROLE ACCOUNTADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;
GRANT IMPORTED PRIVILEGES ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;

-- Step 2: Grant direct access to the Fivetran service account role
-- This allows your roles to inherit permissions from the Fivetran service role
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE ACCOUNTADMIN;
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE MERCURIOS_ADMIN;
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE MERCURIOS_ANALYST;

-- Step 3: Grant usage on database
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;

-- Step 4: Grant usage on all schemas (using INFORMATION_SCHEMA to get all schema names)
-- This is a dynamic approach that will grant usage on all schemas in the database
-- For ACCOUNTADMIN
GRANT USAGE ON ALL SCHEMAS IN DATABASE MERCURIOS_DATA TO ROLE ACCOUNTADMIN;

-- For MERCURIOS_ADMIN
GRANT USAGE ON ALL SCHEMAS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;

-- For MERCURIOS_ANALYST
GRANT USAGE ON ALL SCHEMAS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;

-- For MERCURIOS_DEVELOPER (limited to PUBLIC and RAW)
GRANT USAGE ON SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_DEVELOPER;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_DEVELOPER;

-- Step 5: Grant select on all tables in all schemas
-- For ACCOUNTADMIN
GRANT SELECT ON ALL TABLES IN DATABASE MERCURIOS_DATA TO ROLE ACCOUNTADMIN;

-- For MERCURIOS_ADMIN
GRANT SELECT ON ALL TABLES IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;

-- For MERCURIOS_ANALYST
GRANT SELECT ON ALL TABLES IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;

-- For MERCURIOS_DEVELOPER (limited to PUBLIC and RAW)
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_DEVELOPER;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_DEVELOPER;

-- Step 6: Grant future privileges
-- For ACCOUNTADMIN
GRANT SELECT ON FUTURE TABLES IN DATABASE MERCURIOS_DATA TO ROLE ACCOUNTADMIN;

-- For MERCURIOS_ADMIN
GRANT SELECT ON FUTURE TABLES IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;

-- For MERCURIOS_ANALYST
GRANT SELECT ON FUTURE TABLES IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;

-- For MERCURIOS_DEVELOPER (limited to PUBLIC and RAW)
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_DEVELOPER;

-- Step 7: Grant monitor privileges for Fivetran metadata
GRANT MONITOR ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;
GRANT MONITOR ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;
