-- Snowflake Access Grant Script for Mercurios AI Project
-- Run these commands as ACCOUNTADMIN to grant access to Fivetran schemas

-- Step 1: Grant usage on database to roles
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;

-- Step 2: Grant usage on schemas to roles
-- For MERCURIOS_ADMIN (full access)
GRANT USAGE ON SCHEMA MERCURIOS_DATA."GOOGLE_ANALYTICS_4" TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON SCHEMA MERCURIOS_DATA."KLAVIYO" TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON SCHEMA MERCURIOS_DATA."KLAVIYO_KLAVIYO" TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON SCHEMA MERCURIOS_DATA."KLAVIYO_INT_KLAVIYO" TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON SCHEMA MERCURIOS_DATA."KLAVIYO_STG_KLAVIYO" TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON SCHEMA MERCURIOS_DATA."FIVETRAN_ARMED_UNLEADED_STAGING" TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON SCHEMA MERCURIOS_DATA."FIVETRAN_METADATA" TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON SCHEMA MERCURIOS_DATA."FIVETRAN_METADATA_FIVETRAN_PLATFORM" TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON SCHEMA MERCURIOS_DATA."FIVETRAN_METADATA_STG_FIVETRAN_PLATFORM" TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_ADMIN;

-- For MERCURIOS_ANALYST (read access)
GRANT USAGE ON SCHEMA MERCURIOS_DATA."GOOGLE_ANALYTICS_4" TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON SCHEMA MERCURIOS_DATA."KLAVIYO" TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON SCHEMA MERCURIOS_DATA."KLAVIYO_KLAVIYO" TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON SCHEMA MERCURIOS_DATA."KLAVIYO_INT_KLAVIYO" TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON SCHEMA MERCURIOS_DATA."KLAVIYO_STG_KLAVIYO" TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_ANALYST;

-- For MERCURIOS_DEVELOPER (development access)
GRANT USAGE ON SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_DEVELOPER;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_DEVELOPER;

-- Step 3: Grant select on all tables in schemas
-- For MERCURIOS_ADMIN (full access)
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA."GOOGLE_ANALYTICS_4" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO_KLAVIYO" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO_INT_KLAVIYO" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO_STG_KLAVIYO" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA."FIVETRAN_ARMED_UNLEADED_STAGING" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA."FIVETRAN_METADATA" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA."FIVETRAN_METADATA_FIVETRAN_PLATFORM" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA."FIVETRAN_METADATA_STG_FIVETRAN_PLATFORM" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_ADMIN;

-- For MERCURIOS_ANALYST (read access)
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA."GOOGLE_ANALYTICS_4" TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO" TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO_KLAVIYO" TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO_INT_KLAVIYO" TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO_STG_KLAVIYO" TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_ANALYST;

-- For MERCURIOS_DEVELOPER (development access)
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_DEVELOPER;
GRANT SELECT ON ALL TABLES IN SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_DEVELOPER;

-- Step 4: Grant future privileges (for new tables that will be created)
-- For MERCURIOS_ADMIN (full access)
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA."GOOGLE_ANALYTICS_4" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO_KLAVIYO" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO_INT_KLAVIYO" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO_STG_KLAVIYO" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA."FIVETRAN_ARMED_UNLEADED_STAGING" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA."FIVETRAN_METADATA" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA."FIVETRAN_METADATA_FIVETRAN_PLATFORM" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA."FIVETRAN_METADATA_STG_FIVETRAN_PLATFORM" TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_ADMIN;

-- For MERCURIOS_ANALYST (read access)
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA."GOOGLE_ANALYTICS_4" TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO" TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO_KLAVIYO" TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO_INT_KLAVIYO" TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA."KLAVIYO_STG_KLAVIYO" TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_ANALYST;

-- For MERCURIOS_DEVELOPER (development access)
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_DEVELOPER;

-- Step 5: Grant create table permissions to MERCURIOS_ADMIN and MERCURIOS_DEVELOPER
GRANT CREATE TABLE ON SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_ADMIN;
GRANT CREATE TABLE ON SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_ADMIN;
GRANT CREATE TABLE ON SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_DEVELOPER;

-- Step 6: Grant imported privileges for Fivetran-managed schemas
-- This is critical for accessing the Fivetran-managed schemas
GRANT IMPORTED PRIVILEGES ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;

-- Step 7: Create a role for Fivetran service and grant necessary permissions
-- Only run this if you need to create a new Fivetran service role
-- CREATE ROLE IF NOT EXISTS MERCURIOS_FIVETRAN_SERVICE;
-- GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_FIVETRAN_SERVICE;
-- GRANT USAGE ON SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_FIVETRAN_SERVICE;
-- GRANT USAGE ON SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_FIVETRAN_SERVICE;
