-- Grant Fivetran Service Role to Other Roles
-- This script grants the MERCURIOS_FIVETRAN_SERVICE role to other roles

-- Step 1: Grant the Fivetran service role to other roles
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE ACCOUNTADMIN;
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE MERCURIOS_ADMIN;
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE MERCURIOS_ANALYST;
GRANT ROLE MERCURIOS_FIVETRAN_SERVICE TO ROLE MERCURIOS_DEVELOPER;

-- Step 2: Grant usage on database
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DEVELOPER;

-- Step 3: Grant usage on schemas
GRANT USAGE ON ALL SCHEMAS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ANALYST;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_DEVELOPER;
GRANT USAGE ON SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_DEVELOPER;
