
    -- Create a materialized view for the dashboard
    CREATE OR REPLACE MATERIALIZED VIEW MERCURIOS_DATA.ANALYTICS.BUSINESS_DASHBOARD_MV
    AS SELECT * FROM MERCURIOS_DATA.ANALYTICS.BUSINESS_DASHBOARD;
    
    -- Create a task to refresh the materialized view
    CREATE OR REPLACE TASK MERCURIOS_DATA.ADMIN.REFRESH_DASHBOARD_MV
      WAREHOUSE = MERCURIOS_ANALYTICS_WH
      SCHEDULE = 'USING CRON 0 3 * * * Europe/Berlin'
    AS
      REFRESH MATERIALIZED VIEW MERCURIOS_DATA.ANALYTICS.BUSINESS_DASHBOARD_MV;
    
    -- Initially suspend the task
    ALTER TASK MERCURIOS_DATA.ADMIN.REFRESH_DASHBOARD_MV SUSPEND;
    