-- Snowflake Authentication Configuration
-- This script configures longer session timeouts to reduce MFA prompts

-- Set network policy with longer session timeout (8 hours)
CREATE OR REPLACE NETWORK POLICY MERCURIOS_NETWORK_POLICY
  ALLOWED_IP_LIST = ('0.0.0.0/0')  -- This allows all IPs, restrict as needed for security
  BLOCKED_IP_LIST = ()
  COMMENT = 'Network policy for Mercurios with extended session timeout';

-- Apply network policy to your account
ALTER ACCOUNT SET NETWORK_POLICY = MERCURIOS_NETWORK_POLICY;

-- Set longer session timeout for your user
ALTER USER JULIUSRECHENBACH SET 
  DEFAULT_ROLE = 'ACCOUNTADMIN'
  DEFAULT_WAREHOUSE = 'MERCURIOS_ANALYTICS_WH'
  DEFAULT_NAMESPACE = 'MERCURIOS_DATA.PUBLIC'
  SESSION_TIMEOUT_MINS = 480; -- 8 hours

-- Create a custom role with extended privileges to reduce need for ACCOUNTADMIN
CREATE ROLE IF NOT EXISTS MERCURIOS_ADMIN_ROLE;

-- Grant necessary privileges to the role
GRANT USAGE ON WAREHOUSE MERCURIOS_LOADING_WH TO ROLE MERCURIOS_ADMIN_ROLE;
GRANT USAGE ON WAREHOUSE MERCURIOS_ANALYTICS_WH TO ROLE MERCURIOS_ADMIN_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE MERCURIOS_ADMIN_ROLE;
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA MERCURIOS_DATA.PUBLIC TO ROLE MERCURIOS_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA MERCURIOS_DATA.RAW TO ROLE MERCURIOS_ADMIN_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_ADMIN_ROLE;
GRANT USAGE ON DATABASE GOOGLE_ANALYTICS_4 TO ROLE MERCURIOS_ADMIN_ROLE;
GRANT USAGE ON SCHEMA GOOGLE_ANALYTICS_4.PUBLIC TO ROLE MERCURIOS_ADMIN_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA GOOGLE_ANALYTICS_4.PUBLIC TO ROLE MERCURIOS_ADMIN_ROLE;

-- Grant the role to your user
GRANT ROLE MERCURIOS_ADMIN_ROLE TO USER JULIUSRECHENBACH;

-- For dbt operations, create a dedicated role with necessary permissions
CREATE ROLE IF NOT EXISTS MERCURIOS_DBT_ROLE;

-- Grant necessary privileges to the dbt role
GRANT USAGE ON WAREHOUSE MERCURIOS_ANALYTICS_WH TO ROLE MERCURIOS_DBT_ROLE;
GRANT USAGE ON DATABASE MERCURIOS_DATA TO ROLE MERCURIOS_DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA MERCURIOS_DATA.RAW_STAGING TO ROLE MERCURIOS_DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA MERCURIOS_DATA.RAW_INTERMEDIATE TO ROLE MERCURIOS_DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA MERCURIOS_DATA.RAW_MARTS TO ROLE MERCURIOS_DBT_ROLE;
GRANT USAGE ON DATABASE GOOGLE_ANALYTICS_4 TO ROLE MERCURIOS_DBT_ROLE;
GRANT USAGE ON SCHEMA GOOGLE_ANALYTICS_4.PUBLIC TO ROLE MERCURIOS_DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA GOOGLE_ANALYTICS_4.PUBLIC TO ROLE MERCURIOS_DBT_ROLE;

-- Grant the dbt role to your user
GRANT ROLE MERCURIOS_DBT_ROLE TO USER JULIUSRECHENBACH;
