version: 2

sources:
  - name: prohandel
    description: "Raw data from the ProHandel API via Fivetran"
    database: "{{ var('database', 'mercurios') }}"
    schema: "{{ var('schema', 'public') }}"
    tables:
      - name: article
        description: "Product information"
        columns:
          - name: article_number
            description: "Unique identifier for the article"
            tests:
              - unique
              - not_null
          - name: name
            description: "Article name"
            tests:
              - not_null
          - name: price
            description: "Selling price"
          - name: cost_price
            description: "Cost price"
          - name: last_modified
            description: "Last modification timestamp"
            
      - name: customer
        description: "Customer information"
        columns:
          - name: customer_number
            description: "Unique identifier for the customer"
            tests:
              - unique
              - not_null
          - name: name
            description: "Customer name"
            tests:
              - not_null
              
      - name: order
        description: "Order information"
        columns:
          - name: order_number
            description: "Unique identifier for the order"
            tests:
              - unique
              - not_null
          - name: customer_number
            description: "Reference to the customer"
            tests:
              - not_null
              - relationships:
                  to: source('prohandel', 'customer')
                  field: customer_number
          - name: order_date
            description: "Date when the order was placed"
            tests:
              - not_null
              
      - name: sale
        description: "Sales transactions"
        columns:
          - name: sale_id
            description: "Unique identifier for the sale"
            tests:
              - unique
              - not_null
          - name: order_number
            description: "Reference to the order"
            tests:
              - not_null
          - name: article_number
            description: "Reference to the article"
            tests:
              - not_null
              - relationships:
                  to: source('prohandel', 'article')
                  field: article_number
          - name: quantity
            description: "Quantity sold"
            tests:
              - not_null
          - name: amount
            description: "Total amount of the sale"
            tests:
              - not_null
          - name: sale_date
            description: "Date when the sale occurred"
            tests:
              - not_null
              
      - name: inventory
        description: "Inventory levels"
        columns:
          - name: inventory_id
            description: "Unique identifier for the inventory record"
            tests:
              - unique
              - not_null
          - name: article_number
            description: "Reference to the article"
            tests:
              - not_null
              - relationships:
                  to: source('prohandel', 'article')
                  field: article_number
          - name: warehouse_id
            description: "Reference to the warehouse"
            tests:
              - not_null
          - name: quantity
            description: "Quantity in stock"
            tests:
              - not_null
          - name: last_updated
            description: "Last update timestamp"
            tests:
              - not_null
              
      - name: daily_sales_agg
        description: "Daily sales aggregations"
        columns:
          - name: agg_date
            description: "Aggregation date"
            tests:
              - unique
              - not_null
          - name: total_sales
            description: "Total sales amount for the day"
            tests:
              - not_null
          - name: total_quantity
            description: "Total quantity sold for the day"
            tests:
              - not_null
              
      - name: article_sales_agg
        description: "Sales aggregated by article"
        columns:
          - name: agg_id
            description: "Unique identifier for the aggregation"
            tests:
              - unique
              - not_null
          - name: article_number
            description: "Reference to the article"
            tests:
              - not_null
              - relationships:
                  to: source('prohandel', 'article')
                  field: article_number
          - name: total_sales
            description: "Total sales amount for the article"
            tests:
              - not_null
          - name: total_quantity
            description: "Total quantity sold for the article"
            tests:
              - not_null
              
      - name: warehouse_inventory_agg
        description: "Inventory aggregated by warehouse"
        columns:
          - name: agg_id
            description: "Unique identifier for the aggregation"
            tests:
              - unique
              - not_null
          - name: warehouse_id
            description: "Reference to the warehouse"
            tests:
              - not_null
          - name: total_quantity
            description: "Total quantity in the warehouse"
            tests:
              - not_null
