mercurios:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: VRXDFZX-ZZ95717
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'MERCURIOS_DATA') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'MERCURIOS_ANALYTICS_WH') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'MARTS') }}"
      threads: 4
      client_session_keep_alive: True
