version: 2

models:
  - name: reorder_recommendations
    description: "Generates actionable reorder recommendations based on inventory levels, sales velocity, and safety stock calculations"
    columns:
      - name: tenant_id
        description: "Unique identifier for the tenant"
        tests:
          - not_null
      
      - name: article_id
        description: "Unique identifier for the article"
        tests:
          - not_null
          - unique:
              config:
                where: "tenant_id is not null"
      
      - name: article_name
        description: "Name of the article"
        tests:
          - not_null
      
      - name: current_stock
        description: "Current stock level of the article"
        tests:
          - not_null
          - dbt_utils.not_negative
      
      - name: reorder_point
        description: "Stock level at which a reorder should be triggered"
        tests:
          - not_null
          - dbt_utils.not_negative
      
      - name: economic_order_quantity
        description: "Optimal order quantity to minimize total inventory costs"
        tests:
          - not_null
          - dbt_utils.not_negative
      
      - name: safety_stock
        description: "Buffer stock to protect against stockouts"
        tests:
          - not_null
          - dbt_utils.not_negative
      
      - name: lead_time_days
        description: "Number of days it takes to receive an order after placing it"
        tests:
          - not_null
          - dbt_utils.positive_value
      
      - name: abc_class
        description: "ABC classification of the article (A, B, or C)"
        tests:
          - not_null
          - accepted_values:
              values: ['A', 'B', 'C']
      
      - name: reorder_priority
        description: "Priority of the reorder recommendation (High, Medium, Low)"
        tests:
          - not_null
          - accepted_values:
              values: ['High', 'Medium', 'Low']
      
      - name: days_until_stockout
        description: "Estimated number of days until the article will be out of stock"
        tests:
          - not_null
      
      - name: last_updated_at
        description: "Timestamp when the recommendation was last updated"
        tests:
          - not_null

    tests:
      - dbt_utils.expression_is_true:
          expression: "reorder_point <= economic_order_quantity"
          severity: warn
      
      - dbt_utils.expression_is_true:
          expression: "safety_stock <= reorder_point"
          severity: warn
      
      - dbt_utils.expression_is_true:
          expression: "days_until_stockout >= 0"
          severity: warn
